title: Fractal 1
params:
  footer:
    copyright: '&copy; Untitled.'
    social_icons:
      - icon: fa-facebook
        title: Facebook
        url: '#'
      - icon: fa-twitter
        title: Twitter
        url: '#'
      - icon: fa-instagram
        title: Instagram
        url: '#'
  header:
    actions:
      - icon: fa-download
        is_primary: true
        is_scrolly: false
        label: Download
        url: elements.md
      - icon: fa-chevron-down
        is_primary: false
        is_scrolly: true
        label: Learn More
        url: '#one'
    img:
      path: images/screen.jpg
      phone_border: true
    subtitle: |-
      Nibh sed aliquam, cursus arcu aliquet  
      natoque rhoncus ut non in Aliquet
    title_url: '#'
  palette: blue
  palettes:
    blue:
      sass:
        color: '#4696e5'
    magenta:
      sass:
        color: '#db5c7a'
    purple:
      sass:
        color: '#786dc2'
